### ISSUE TITLE
getting rid of this.props

### ISSUE THREAD

**Issue by Karyum** [facn2/path-18#79]
Just before [this line](https://github.com/facn2/path-18/blob/master/src/components/career_detail.jsx#L13) you should add a const that is equal to this.props.selected so everytime you want to use it later on you just need to do selected.title instead of this.props.selected.title looks much cleaner :maple_leaf: .

**Comment by Karyum** [comment]
@veredrec those were my issues and i love to close them :cry:

**Comment by veredrec** [comment]
@Karyum I'm so sorry! Should I reopen them? :flushed:
